# Site settings
title: Joshua Abraham's Personal Site
description: Jekyll Theme Minimal Resume
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Joshua Abraham
user_description: Hello! My name is Josh Abraham. I am a PhD student at the University of Wisconsin-Madison in the Chemical and Biological Engineering Department. This is my personal site to store quick links for research use, to digitally present my CV, and to keep track of open-source projects. 
user_title: Graduate Student
email: jpabraham@wisc.edu
# twitter_username: Currently Not Available
# github_username:  joshpabraham
# gplus_username:  Currently Not Available

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
